language: php
php:
- 5.4
- 5.5
env:
  matrix:
  - DB=mysql TYPO3=TYPO3_6-2 INTEGRATION=master
  global:
  - secure: A5tBgRS7n+LJ1KcaFeEOGRmNLXrNr5GFuHsM4zoyzfzzcnBSSE3Kyb7sxMG8AgbzUc2zVu4O04TRA/WlTk/3FB/Cvw2TjR0Q6t6rtHgL+S6QDp8+br5f+47f0YUwOyFe6/F2kALV81unEGS51nbUVK+pcRwLfCqElApf4bZrCW0=
  - secure: hMKQj0pNJkQ9gxnhqlf4DEeBEdof3G8eGEn0UISyClroiWniUmEHRO2gNfPvromzw66J9UlOLfUOovOWQAq9osmTMCOdP4We6011n+BoC+Yi0znTNRQPEbGXtQlQyz+ewz60LJ//4wsYNaKz22Hut6sHsAaynA7bAxhEb8/fnDs=
before_script:
- sudo apt-get update && sudo apt-get install git
- cd ..
- git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/ipf/TYPO3-Travis-Integration.git
  build-environment
- git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git
  core
- source build-environment/install-helper.sh
- git clone --single-branch --branch $INTEGRATION --depth 1 git://git.typo3.org/TYPO3CMS/Distributions/Introduction.git
  build-environment/Introduction
- mv core/typo3 .
- if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
- mv build-environment/typo3conf .
- mkdir fileadmin
- mkdir uploads
- mkdir typo3temp
- git clone --depth 1 --single-branch --branch $TRAVIS_BRANCH https://github.com/subugoe/typo3-tmpl_adw.git
  typo3conf/ext/tmpl_adw
- git clone --depth 1 git://git.typo3.org/TYPO3CMS/Extensions/phpunit.git typo3conf/ext/phpunit
- git clone --depth 1 git://github.com/FluidTYPO3/builder.git typo3conf/ext/builder
- if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;"
  -uroot; fi
- if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql;
  fi
- if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then
  mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
- if [[ "$DB" == "mysql" && -f build-environment/dbimport/cli_users.sql ]]; then mysql
  -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
- if [[ "$DB" == "mysql" && -f build-environment/dbimport/phpunit.sql ]]; then mysql
  -uroot typo3_test < build-environment/dbimport/phpunit.sql; fi
script:
- typo3/cli_dispatch.phpsh phpunit typo3conf/ext/tmpl_adw;
addons:
  sauce_connect: true
